USE surno;

SHOW TABLES;

DESCRIBE USERS;

DESCRIBE CAMIONEROS;


SELECT * FROM PAQUETES;

INSERT INTO USERS (usuario, pass, rol) VALUES ('lorenzo', 'pass','2');

SELECT * FROM USERS;

UPDATE USERS SET usuario = 'lorenzo' WHERE 1;

ALTER TABLE ESTADOS ADD sasasa INT;

CREATE TABLE CLIEN (
    RUT CHAR(12) PRIMARY KEY,
    nombre VARCHAR(32) NOT NULL,
    baja BIT DEFAULT 0 NOT NULL
);

DROP TABLE LOTES;

TRUNCATE TABLE USERS;

SELECT * FROM VEHICULOS;

INSERT INTO PAQUETES (ID_almacen, ID_pickup, calle, numero, ciudad, mail) VALUES (1,5,'sasasa','2432','montevideo','jijlij@jlkjkl');

SELECT * FROM PAQUETES;

UPDATE PAQUETES SET fecha_recibido = CURRENT_TIMESTAMP WHERE ID=4;

UPDATE PAQUETES SET volumen = 23423 WHERE ID=4;

UPDATE PAQUETES SET volumen = 23423 WHERE ID=4;

SELECT * FROM TRAE;

INSERT INTO TRAE (ID_paquete,matricula) VALUES (4,'ABC1234');

UPDATE TRAE SET fecha_descarga= CURRENT_TIMESTAMP WHERE ID_paquete=4;

DELETE FROM PAQUETES WHERE ID=4;
